---
- hosts: tower
  become: yes
#  gather_facts: False
  tasks:
   - name: checking if the file 1 exists
     stat:
       path: /home/vagrant/test/file1.txt
     register: stat_r
   - debug:
       msg: "Path exists and is a file"
     when: stat_r.stat.exists and stat_r.stat.isreg

   - name: moving file 1
     command: mv /home/vagrant/test/file1.txt /tmp
     when: stat_r.stat.exists == True
